/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.views;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class CalculadoraG extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraG
     */
    
    private double firstValue;
    private double secondValue;
    private double resultValue;
    
    public CalculadoraG() {
        initComponents();
        DefaultDesing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFirstValue = new java.awt.TextField();
        jlSecondValue = new javax.swing.JLabel();
        jlFirstValue = new javax.swing.JLabel();
        txtResultValue = new java.awt.TextField();
        jbtnDiv = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnSubs = new javax.swing.JButton();
        jbtnMult = new javax.swing.JButton();
        jbtnEquals = new javax.swing.JButton();
        jlResult = new javax.swing.JLabel();
        txtSecondValue = new java.awt.TextField();
        jbtnReset = new javax.swing.JButton();
        jlCreator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(20, 20, 20));

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        txtFirstValue.setBackground(new java.awt.Color(30, 30, 30));
        txtFirstValue.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtFirstValue.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstValue.setText("0");

        jlSecondValue.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlSecondValue.setForeground(new java.awt.Color(255, 255, 255));
        jlSecondValue.setText("Second value:");

        jlFirstValue.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlFirstValue.setForeground(new java.awt.Color(255, 255, 255));
        jlFirstValue.setText("First value: ");

        txtResultValue.setBackground(new java.awt.Color(30, 30, 30));
        txtResultValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtResultValue.setEditable(false);
        txtResultValue.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtResultValue.setForeground(new java.awt.Color(255, 255, 255));
        txtResultValue.setText("0");
        txtResultValue.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtResultValuePropertyChange(evt);
            }
        });

        jbtnDiv.setBackground(new java.awt.Color(0, 102, 102));
        jbtnDiv.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jbtnDiv.setText("/");
        jbtnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDivMouseClicked(evt);
            }
        });

        jbtnPlus.setBackground(new java.awt.Color(0, 102, 102));
        jbtnPlus.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPlusMouseClicked(evt);
            }
        });

        jbtnSubs.setBackground(new java.awt.Color(0, 102, 102));
        jbtnSubs.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jbtnSubs.setText("-");
        jbtnSubs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSubsMouseClicked(evt);
            }
        });

        jbtnMult.setBackground(new java.awt.Color(0, 102, 102));
        jbtnMult.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jbtnMult.setText("X");
        jbtnMult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnMultMouseClicked(evt);
            }
        });

        jbtnEquals.setBackground(new java.awt.Color(0, 102, 102));
        jbtnEquals.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jbtnEquals.setText("=");
        jbtnEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEqualsMouseClicked(evt);
            }
        });

        jlResult.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlResult.setForeground(new java.awt.Color(255, 255, 255));
        jlResult.setText("Result:");

        txtSecondValue.setBackground(new java.awt.Color(30, 30, 30));
        txtSecondValue.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtSecondValue.setForeground(new java.awt.Color(255, 255, 255));
        txtSecondValue.setText("0");

        jbtnReset.setBackground(new java.awt.Color(0, 102, 102));
        jbtnReset.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jbtnReset.setText("C");
        jbtnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
        });

        jlCreator.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jlCreator.setForeground(new java.awt.Color(255, 255, 255));
        jlCreator.setText("Designed by Jean Smith");
        jlCreator.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlResult, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultValue, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnPlus)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSubs)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDiv)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnMult)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnEquals))
                            .addComponent(jlSecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtFirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jlFirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(txtSecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtFirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jlSecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPlus)
                    .addComponent(jbtnSubs)
                    .addComponent(jbtnDiv)
                    .addComponent(jbtnMult)
                    .addComponent(jbtnEquals))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jlResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jlCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jlFirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(272, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(txtSecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultValuePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtResultValuePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultValuePropertyChange

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked
        // TODO add your handling code here:
        this.DefaultDesing();
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jbtnPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPlusMouseClicked
        // TODO add your handling code here:
        this.firstValue = Double.parseDouble(this.txtFirstValue.getText());
        this.secondValue = Double.parseDouble(this.txtSecondValue.getText());
        this.resultValue = this.firstValue + this.secondValue;
        
        this.txtResultValue.setText("" + resultValue);
    }//GEN-LAST:event_jbtnPlusMouseClicked

    private void jbtnSubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSubsMouseClicked
        // TODO add your handling code here:
        this.firstValue = Double.parseDouble(this.txtFirstValue.getText());
        this.secondValue = Double.parseDouble(this.txtSecondValue.getText());
        this.resultValue = this.firstValue - this.secondValue;
        
        this.txtResultValue.setText("" + resultValue);
    }//GEN-LAST:event_jbtnSubsMouseClicked

    private void jbtnDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDivMouseClicked
        // TODO add your handling code here:
        this.firstValue = Double.parseDouble(this.txtFirstValue.getText());
        this.secondValue = Double.parseDouble(this.txtSecondValue.getText());
        
        if (this.secondValue != 0)        
        {
            this.resultValue = this.firstValue / this.secondValue;
            this.txtResultValue.setText("" + resultValue);
        }
        
        else
        {
            JOptionPane.showMessageDialog(this.jPanel1, "La división por cero no está definida");
            this.txtResultValue.setText("ERROR");
        }
        
    }//GEN-LAST:event_jbtnDivMouseClicked

    private void jbtnMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnMultMouseClicked
        // TODO add your handling code here:
        this.firstValue = Double.parseDouble(this.txtFirstValue.getText());
        this.secondValue = Double.parseDouble(this.txtSecondValue.getText());
        this.resultValue = this.firstValue * this.secondValue;
        
        this.txtResultValue.setText("" + resultValue);
    }//GEN-LAST:event_jbtnMultMouseClicked

    private void jbtnEqualsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEqualsMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this.jPanel1, "Sin funcionalidad por ahora");
    }//GEN-LAST:event_jbtnEqualsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnEquals;
    private javax.swing.JButton jbtnMult;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSubs;
    private javax.swing.JLabel jlCreator;
    private javax.swing.JLabel jlFirstValue;
    private javax.swing.JLabel jlResult;
    private javax.swing.JLabel jlSecondValue;
    private java.awt.TextField txtFirstValue;
    private java.awt.TextField txtResultValue;
    private java.awt.TextField txtSecondValue;
    // End of variables declaration//GEN-END:variables

    private void DefaultDesing()
    {
        this.setResizable(false);
        this.txtFirstValue.setText("0");
        this.txtSecondValue.setText("0");
        this.txtResultValue.setText("0");
    }
}
